---
# This playbook configures log rotation for the custom-monitor systemd service logs
#  and ensures the log directory exists with correct permissions.

- name: Configure log rotation for custom-monitor.service logs
  hosts: sre-log-rotate
  become: true
  vars:
    custom_monitor_log_dir: /var/log/custom-monitor
    custom_monitor_logrotate_conf: /etc/logrotate.d/custom-monitor
    prune_run: false

  tasks:
  # Verify/create log directory with 0755 permission
    - name: Verify/create log directory with 0755 permission
      file:
        path: "{{ custom_monitor_log_dir }}"
        state: directory
        mode: "0755"

# Deploy logrotate config by using jinja2 template in templates/custom-monitor.logrotate.j2
    - name: Deploy logrotate config
      template:
        src: custom-monitor.logrotate.j2
        dest: "{{ custom_monitor_logrotate_conf }}"
        mode: "0644"

  # - Prune logs after 30 days 
    - name: Prune logs after 30 days
      command:
        cmd: "find {{ custom_monitor_log_dir }} -type f -mtime +30 -delete"
      when: "prune_run == true"
        
    
    # Fail if directory is higher than 500MB
    - name: Fail if directory is higher than 500MB
      shell: "du -b {{ custom_monitor_log_dir }} | awk '{print $1}'"
      register: filesize_output
      failed_when: "{{ filesize_output.stdout | int }} > (500 * 1024 * 1024)"
